{% set name = "keras-cv" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/5e/3b/b430a70b14f593f6c9a371285af3b9c7c6e4b024b8a999c6dccfab959d5f/keras_cv-0.4.2-py3-none-any.whl
  sha256: 74779a9177af1e94729e9f4eaabc0339fe99e1d8b6b20dd03c55ed5b38588868

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - absl-py >=1
    - packaging
    - python >=3.7
    - tensorflow >=2.9.0
    - tensorflow-datasets
    - regex

test:
  imports:
    - keras_cv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/keras-team/keras-cv
  summary: Industry-strength computer Vision extensions for Keras.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
