{% set name = "keras-cv" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/keras-team/keras-cv/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c6fdbb020f8d43b6ed4bd61b034b0054ee42b0eb2cbb111962b3bd849b3209ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - absl-py
    - packaging
    - python >=3.7
    - tensorflow >=2.11.0
    - tensorflow-datasets
    - regex
    - keras-core
    - kagglehub

test:
  imports:
    - keras_cv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/keras-team/keras-cv
  summary: Industry-strength computer Vision extensions for Keras.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
