{% set name = "keras-cv" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/keras-cv-{{ version }}.tar.gz
  sha256: 23691320109f3e6fa745e60b023eb0deec101559ed92dc023d568a71613dc70e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - absl-py >=1
    - packaging
    - python >=3.7
    - tensorflow >=2.9.0
    - tensorflow-datasets

test:
  imports:
    - keras_cv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/keras-team/keras-cv
  summary: Industry-strength computer Vision extensions for Keras.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
