{% set name = "keras-cv" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/keras-cv-{{ version }}.tar.gz
  sha256: 6d36629611343aed2928c40b64f9e9d4fdc2c8814136223c1255ae41303488d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - absl-py
    - packaging
    - python >=3.7
  run_constrained:
    - tensorflow >=2.9.0

test:
  # imports would only work with tensorflow present
  # but since depends on 2.9.0 (still not available on cf)
  # will activate this import test later
  #imports:
    #- keras_cv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/keras-team/keras-cv
  summary: Industry-strength computer Vision extensions for Keras.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
